import "./globals.css";
import { Inter } from "next/font/google";
import {  Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ChatMinds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>
          ChatMinds
        </title>
      </head>
      <body className={inter.className + " h-full"}>
      <Toaster position="top-right" /> 
          {children}
      </body>
    </html>
  );
}
